name: Go Build
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build
        working-directory: ./src
        run: go build -v ./...
      - name: Test
        working-directory: ./src
        run: go test -v ./...