name: Create Release
on:
  pull_request:
    types: closed
    branches: 'main'

jobs:
  check-src-changes:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      changes: steps.changes.outputs.changes
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/**'

  release-container:
    needs: check-src-changes
    if: ${{ needs.check-src-changes.outputs.changes != '[]' }}
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      DOCKERFILE_PATH: ./src/Dockerfile
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0

      - name: Bump version and push tag
        if: ${{ needs.check-src-changes.outputs.changes != '[]' }}
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'ghcr login'
        if: ${{ needs.check-src-changes.outputs.changes != '[]' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Image'
        if: ${{ needs.check-src-changes.outputs.changes != '[]' }}
        run: |
          docker build \
          -t ghcr.io/${{ github.repository }}:${{steps.tag_version.outputs.new_tag}} \
          -f ${{ env.DOCKERFILE_PATH }} \
          --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
          --label "org.opencontainers.image.description=${{ github.repository }}" \
          --label "org.opencontainers.image.licenses=MIT" .

          docker push ghcr.io/${{ github.repository }}:${{steps.tag_version.outputs.new_tag}}

      - name: Create a GitHub release
        if: ${{ needs.check-src-changes.outputs.changes != '[]' }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

  chart-release:
    if: github.event.pull_request.merged == true
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${{ github.repository_owner }}"
          git config user.email "${{ github.repository_owner }}@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
