name: Create Release Tag
on:
  pull_request:
    types: closed
    branches: 'main'
jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1

      - name: echo version
        run: |
          echo ${{ steps.version.outputs.version }}

      - uses: thejeff77/action-push-tag@v1.0.0
        with:
          tag: ${{ steps.version.outputs.version }}
          message: "${{ steps.version.outputs.version }} ${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}"
