name: Create Release
on:
  push:
    tags: "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: grafana-user-sync
      DOCKERFILE_PATH: ./Dockerfile
    steps:
      - name: Find tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: echo tag
        run: echo ${{steps.tag.outputs.tag}}

      - name: 'ghcr login'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Image'
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{steps.tag.outputs.tag}} -f ${{ env.DOCKERFILE_PATH }} .
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{steps.tag.outputs.tag}}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.tag.outputs.tag}}
          release_name: v${{steps.tag.outputs.tag}}
          draft: true

      - name: Publish latest release
        uses: logicoversnacks/actions-publish@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        with:
          repo: ${{ github.repository }}