name: Release Helm Chart
on:
  push:
    tags: "v*.*.*"
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            charts:
              - 'charts/**'

      - name: Install Helm
        if: steps.changes.outputs.charts == 'true'
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        if: steps.changes.outputs.charts == 'true'
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"